### ISSUE TITLE
Update required libraries for deprecated Google Play Services SDKs

### ISSUE THREAD

**Issue by edharkhimich** [rudderlabs/rudder-integration-branch-android#6]
**_com.rudderstack.android.integration:branch:0.1.3_**

Our application's latest production release is flagged by the Google Play Console due to the use of outdated Google Play Services SDKs. This is causing SDK issues that could prevent future releases and affect the application's rudderstack functionalities.

**Affected SDK**
It appears that the com.rudderstack.android.integration:branch plugin may be internally using outdated versions of Google Play Services SDKs, particularly:

_com.google.android.gms:play-services-ads-lite:16.0.0
com.google.android.gms:play-services-ads:16.0.0_

**Google Play Console Notification**
Google has notified us that the following SDK versions are deprecated:

**_com.google.android.gms:play-services-ads-lite:16.0.0_**

**Recommended Update:** Upgrade to a newer version (19.3.0+).
**Deprecation Date:** December 14, 2023, 00:00 UTC

**_com.google.android.gms:play-services-ads:16.0.0_**

**Recommended Update:** Upgrade to a newer version (19.4.0+).
**Deprecation Note:** This version is officially deprecated and will soon disable ad loading. [Google AdMob Deprecation Policy](https://developers.google.com/admob/android/deprecation)
**Deprecation Date:** December 14, 2023, 00:00 UTC

**Expected Outcome**
The _com.rudderstack.android.integration:branch_ plugin needs to be updated to use the latest versions of Google Play Services SDKs to avoid these issues and ensure continued compliance with Google Play's policies and functionality of ad-related features.

**Comment by 1abhishekpandey** [comment]
Hey @edharkhimich,
Thank you for bringing up the issue. We will investigate it and make efforts to resolve it soon.

**Comment by edharkhimich** [comment]
Hello @1abhishekpandey,

I wanted to check in regarding the upcoming deprecation date mentioned by Google, which is set for December 14, 2023, at 00:00 UTC. Do you think we will be able to address the necessary changes before this deadline? Your insights on this would be greatly appreciated. 

Thank you!

**Comment by 1abhishekpandey** [comment]
Hey @edharkhimich,
I intended to provide you with an update on this release tomorrow, once the official Rudder-Branch documentation is updated. However, the fix has already been released today. You can now use the latest version (`2.0.0`) of the Rudder-Branch integration, which should address this issue:
```
implementation 'com.rudderstack.android.sdk:core:[1.20.1, 2.0.0)'
implementation 'com.rudderstack.android.integration:branch:2.0.0'
```

In case you're utilizing our [Rudder-Branch](https://github.com/rudderlabs/rudder-integration-branch-ios) iOS integration, I recommend updating the integration to the latest version 2.0.0.

**Comment by edharkhimich** [comment]
@1abhishekpandey Thank you for you fast response and update!

**Comment by 1abhishekpandey** [comment]
Rudder-Branch doc has been updated, please follow it if needed: https://www.rudderstack.com/docs/destinations/streaming-destinations/branchio/
